### ISSUE TITLE
Vector3 substract function not working

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#434]
In SDK7

I trued usin the Vector3 substract function like this:

`const direction = path.path[0].subtract(path.path[1])`

VS Studio thinks it's fine, but it doesn't work in the scene and the following is reported on console

```
ncaught (in promise) TypeError: path.path[path.target].subtract is not a function
    at Object.RotateSystem [as fn] (move.ts:83:46)
    at Object.update (index.ts:162:14)
    at eval (initialization.ts:37:29)
    at <anonymous>
```

If we decide to move these kinds of functions to an external library, we can do that, but in that case we should at least make it clear in the type data that it's not a function of the base library

I only tested with this function, but it's likely the case for many other Vector3 functions

**Comment by nearnshaw** [comment]
Note, I confirmed that if I use the alternative `Vector3.subtract(point1, point2)` it works correctly.

So the issue should be just to remove the misleading type data that leads you to think that the other syntax would work
